import getColors from "ui-lib/app/services/getColor";

export const data = {
  data: [
    {
      id: 1,
      name: "Leanne Graham",
      email: "Sincere@april.biz",
      tel: "1-770-736-8031 x56442",
      company: "hildegard.org",
      color: getColors("Leanne Graham"),
    },
    {
      id: 2,
      name: "Ervin Howell",
      email: "Shanna@melissa.tv",
      tel: "1-770-736-8031 x56442",
      company: "anastasia.net",
      color: getColors("Ervin Howell"),
    },
    {
      id: 3,
      name: "Clementine Bauch",
      email: "Nathan@yesenia.net",
      tel: "1-463-123-4447",
      company: "ramiro.info",
      color: getColors("Clementine Bauch"),
    },
    {
      id: 4,
      name: "Patricia Lebsack",
      email: "Julianne.OConner@kory.org",
      tel: "493-170-9623 x156",
      company: "kale.biz",
      color: getColors("Patricia Lebsack"),
    },
    {
      id: 5,
      name: "Chelsey Dietrich",
      email: "Lucio_Hettinger@annie.ca",
      tel: "(254)954-1289",
      company: "demarco.info",
      color: getColors("Chelsey Dietrich"),
    },
    {
      id: 6,
      name: "Mrs. Dennis Schulist",
      email: "Karley_Dach@jasper.info",
      tel: "1-477-935-8478 x6430",
      company: "ola.org",
      color: getColors("Mrs. Dennis Schulist"),
    },
    {
      id: 7,
      name: "Kurtis Weissnat",
      email: "Telly.Hoeger@billy.biz",
      tel: "210.067.6132",
      company: "elvis.io",
      color: getColors("Kurtis Weissnat"),
    },
    {
      id: 8,
      name: "Nicholas Runolfsdottir V",
      email: "Sherwood@rosamond.me",
      tel: "586.493.6943 x140",
      company: "jacynthe.com",
      color: getColors("Nicholas Runolfsdottir V"),
    },
    {
      id: 9,
      name: "Glenna Reichert",
      email: "Chaim_McDermott@dana.io",
      tel: "(775)976-6794 x41206",
      company: "conrad.com",
      color: getColors("Glenna Reichert"),
    },
    {
      id: 10,
      name: "Clementina DuBuque",
      email: "Rey.Padberg@karina.biz",
      tel: "024-648-3804",
      company: "ambrose.net",
      color: getColors("Clementina DuBuque"),
    },
  ],
};
export default data;
